### ISSUE TITLE
[Firefox] Can't rearrange videos in folders

### ISSUE THREAD

**Issue by oyale** [MohamedBakoush/WatchVideoByLink#71]
**Describe the bug**
When dragging and dropping, instead of reordering the videos inside the folders, it jumps to the player.

**To Reproduce**
1. Open WatchVideoByLink in Firefox.
2. Go to `saved videos`.
3. Click on any video, hold it and drag it to a folder.
4. The video appears to move to the folder
5. The video player is displayed.
6. Returns to `saved videos`. The video is in the original path.

**Expected behavior**
5. Folder view is shown and the video is within the folder.

**What device are you on?**
Desktop

**Additional context**
WatchVideoByLink: Latest build running in docker container running on centos (using `docker-compose.yml` from repository)
Firefox: 95.0.2 (64-bit) running on W10.

I can't reproduce this on Chrome.

**JS Console errors**:
```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. folder.js:197:1
    inputSelectedIDIntoFolderID https://localhost/scripts/folder.js:197
    AsyncFunctionThrow self-hosted:699
    (Asíncrono: async)
    _onDragEnd https://localhost/scripts/showAvailableVideos.js:501
    (Asíncrono: EventListener.handleEvent)
    dragDropAvailableVideoDetails https://localhost/scripts/showAvailableVideos.js:349
    forEach self-hosted:208
    dragDropAvailableVideoDetails https://localhost/scripts/showAvailableVideos.js:347
    (Asíncrono: EventListener.handleEvent)
    dragDropAvailableVideoDetails https://localhost/scripts/showAvailableVideos.js:343
    folderOnClick https://localhost/scripts/showAvailableVideos.js:332
    onclick https://localhost/scripts/showAvailableVideos.js:274

```
**Screenshot**
(It's a gif, click it to view)
![wvbl_bug](https://user-images.githubusercontent.com/25091358/147665953-6e0dd2da-5f54-4313-9faa-f75a303184c1.gif)

**Comment by MohamedBakoush** [comment]
Interesting. It seems when dropping a draggle element firefox wants to redirect to elements href.
Only happens when dropping above an element containing dragDropContainer as a class.
Happens for both video and folder - video on video, video on folder, folder on video etc etc.


**Lucky this isn't a terrible bug to fix**
  
At file showAvailableVideos.js, function dragDropAvailableVideoDetails (line 337)

Under dragDropContainers.forEach (line 347) add

```
container.addEventListener("drop", _onDragDrop, false);  
```

Under IfElse statement (same as _onDragOver, _onDragEnd functions) add

```
function _onDragDrop(e) { 
  e.preventDefault();  // Stops browsers from redirecting.
}
```
This should do the trick
 
Also for good measure adding `e.stopPropagation();` (Stops parent elements from receiving event) should also be done to dragstart, _onDragOver, _onDragEnd, _onDragDrop

@oyale as you found the bug would you like to fix it?

**References**
https://stackoverflow.com/questions/20354439/html5-drag-drop-e-stoppropagation
